server:
  port: 8090

spring:
  application:
    name: patient-service

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/patient_db
    username: postgres
    password: postgre

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka